"""empty message

Revision ID: 0ea1e15f839e
Revises: 1e707cf62e1e
Create Date: 2026-04-20 16:30:03.129751

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ea1e15f839e"
down_revision: Union[str, Sequence[str], None] = "1e707cf62e1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_follows",
        sa.Column("follower_id", sa.UUID(), nullable=False),
        sa.Column("followed_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["followed_id"],
            ["users.id"],
            name=op.f("fk_user_follows_followed_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
            name=op.f("fk_user_follows_follower_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "follower_id", "followed_id", name=op.f("pk_user_follows")
        ),
    )
    op.create_unique_constraint(
        "uq_comment_user_like", "comment_likes", ["comment_id", "user_id"]
    )
    op.create_index(
        op.f("ix_comments_parent_id"), "comments", ["parent_id"], unique=False
    )
    op.create_index(op.f("ix_comments_pin_id"), "comments", ["pin_id"], unique=False)
    op.create_unique_constraint("uq_pin_user_like", "pin_likes", ["pin_id", "user_id"])
    op.create_index(op.f("ix_pins_created_at"), "pins", ["created_at"], unique=False)
    op.create_index(op.f("ix_pins_owner_id"), "pins", ["owner_id"], unique=False)
    op.create_unique_constraint(op.f("uq_tags_name"), "tags", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_tags_name"), "tags", type_="unique")
    op.drop_index(op.f("ix_pins_owner_id"), table_name="pins")
    op.drop_index(op.f("ix_pins_created_at"), table_name="pins")
    op.drop_constraint("uq_pin_user_like", "pin_likes", type_="unique")
    op.drop_index(op.f("ix_comments_pin_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_parent_id"), table_name="comments")
    op.drop_constraint("uq_comment_user_like", "comment_likes", type_="unique")
    op.drop_table("user_follows")
    # ### end Alembic commands ###
